### PR TITLE
Update to Blender 2.93 alpha

### PR DESCRIPTION
**Pull request by RedHaloStudio**
Update to Blender 2.93 alpha

### CODE REVIEW

**Comment by gurkanerol** [comment]
When will the mac version for 2.9 be released?

**Comment by mahedihasan121** [comment]
any updates? for 2.9

**Comment by lvkesimmons** [comment]
I am also interested in the Mac version!

Terminal showed this error message:

addon not loaded: 'sketchup_importer'
cause: cannot import name 'sketchup' from partially initialized module 'sketchup_importer' (most likely due to a circular import) (/Users/lvkesimmons/Library/Application Support/Blender/3.2/scripts/addons/sketchup_importer/__init__.py)

**Comment by etqa** [comment]
Hello, why does this problem appear when importing if the file has Component:
Python: Traceback (most recent call last):
   File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 1039, in execute
     return SceneImporter().set_filename(keywords['filepath']).load(
   File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 276, in load
     self.write_duplicateable_groups()
   File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 318, in write_duplicateable_groups
     component_stats = self.analyze_entities(
   File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\__init__.py", line 389, in analyze_entities
     cdef = self.skp_components[instance.definition.name]
   File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\sketchup_importer\SKPutil\__init__.py", line 29, in __getitem__
     return dict.__getitem__(self, key)
KeyError: 'Component120#1'

**Pull request closed without merging**
